# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Options:
 require-passing-tests-on: ['Linux']

Dependencies:
 - 'on': ['Linux/Qt6', 'Linux/Qt6Next', 'FreeBSD/Qt6', 'Windows/Qt6']
   'require':
    'frameworks/extra-cmake-modules': 'Frameworks/6.24'
    'frameworks/kcoreaddons': 'Frameworks/6.24'
    'frameworks/kconfig': 'Frameworks/6.24'
    'frameworks/ki18n': 'Frameworks/6.24'
    'frameworks/kitemmodels': 'Frameworks/6.24'
    'frameworks/kcontacts': 'Frameworks/6.24'
    'frameworks/kirigami': 'Frameworks/6.24'
    'frameworks/kdbusaddons': 'Frameworks/6.24'
    'frameworks/knotifications': 'Frameworks/6.24'
    'frameworks/kiconthemes': 'Frameworks/6.24'
    'frameworks/kio': 'Frameworks/6.24'
    'frameworks/kcmutils': 'Frameworks/6.24'
    'frameworks/kservice': 'Frameworks/6.24'
    'frameworks/solid': 'Frameworks/6.24'
    'frameworks/kpeople': 'Frameworks/6.24'
    'frameworks/kwindowsystem': 'Frameworks/6.24'
    'frameworks/qqc2-desktop-style': 'Frameworks/6.24'
    'libraries/kirigami-addons': 'v1.11.0'
 - 'on': ['Linux/Qt6', 'Linux/Qt6Next', 'FreeBSD/Qt6']
   'require':
    'frameworks/kpackage': 'Frameworks/6.24'
    'frameworks/kstatusnotifieritem': 'Frameworks/6.24'
    'libraries/pulseaudio-qt': 'v1.7.0'
    'libraries/plasma-wayland-protocols': 'Frameworks/6.24'
 - 'on': ['Linux/Qt6', 'Linux/Qt6Next']
   'require':
    'frameworks/modemmanager-qt': 'Frameworks/6.24'
