[Desktop Entry]
Type=Application
Exec=${LIBEXEC_INSTALL_DIR}/kdeconnectd
X-KDE-StartupNotify=false
X-KDE-autostart-phase=0
X-GNOME-Autostart-enabled=true
OnlyShowIn=KDE;GNOME;Unity;XFCE;
NoDisplay=true

Name=KDEConnect daemon
Name[bg]=Услуга KDE Connect
Name[ca]=Dimoni del KDEConnect
Name[cs]=Démon KDE Connect
Name[de]=KDE-Connect-Dienst
Name[en_GB]=KDEConnect daemon
Name[es]=Demonio de KDE Connect
Name[fi]=KDEConnect-taustapalvelu
Name[fr]=Démon KDE Connect
Name[gl]=Servizo de KDE Connect
Name[hu]=KDEConnect szolgáltatás
Name[it]=Demone KDE Connect
Name[nl]=KDEConnect-daemon
Name[nn]=KDEConnect-teneste
Name[pl]=Usługa KDEConnect
Name[pt]=Serviço do KDE Connect
Name[pt_BR]=Serviço do KDE Connect
Name[sk]=KDEConnect démon
Name[sv]=Demon för KDE-anslut
Name[tr]=KDEConnect süreci
Name[uk]=Фонова служба KDEConnect
Name[x-test]=xxKDEConnect daemonxx
Name[zh_CN]=KDEConnect 守护进程
