/**
 * SPDX-FileCopyrightText: 2025 James Padgett <snotacusnexus@gmail.com>
 *
 * SPDX-License-Identifier: GPL-2.0-only OR GPL-3.0-only OR LicenseRef-KDE-Accepted-GPL
 */

#include "hyprlandremoteinput.h"

#include <QDebug>
#include <QGuiApplication>
#include <QProcess>
#include <QTime>

#include <linux/input.h>
#include <xkbcommon/xkbcommon.h>

#include <cstring>
#include <memory>
#include <unistd.h>

#include <fcntl.h>
#include <sys/mman.h>

#include <wayland-client.h>

// Generated protocol headers (generated by ECM's ecm_add_wayland_client_protocol)
#include "wayland-virtual-keyboard-client-protocol.h"
#include "wayland-virtual-pointer-client-protocol.h"

// Translation table matching the existing implementations
// Must stay in sync with SpecialKeysMap in waylandremoteinput.cpp and x11remoteinput.cpp
static const int SpecialKeysMap[] = {
    0, // 0: Invalid
    KEY_BACKSPACE, // 1
    KEY_TAB, // 2
    KEY_LINEFEED, // 3
    KEY_LEFT, // 4
    KEY_UP, // 5
    KEY_RIGHT, // 6
    KEY_DOWN, // 7
    KEY_PAGEUP, // 8
    KEY_PAGEDOWN, // 9
    KEY_HOME, // 10
    KEY_END, // 11
    KEY_ENTER, // 12
    KEY_DELETE, // 13
    KEY_ESC, // 14
    KEY_SYSRQ, // 15
    KEY_SCROLLLOCK, // 16
    0, // 17
    0, // 18
    0, // 19
    0, // 20
    KEY_F1, // 21
    KEY_F2, // 22
    KEY_F3, // 23
    KEY_F4, // 24
    KEY_F5, // 25
    KEY_F6, // 26
    KEY_F7, // 27
    KEY_F8, // 28
    KEY_F9, // 29
    KEY_F10, // 30
    KEY_F11, // 31
    KEY_F12, // 32
};

// Button mapping from KDE Connect internal codes to evdev codes
static constexpr int BTN_KDE_LEFT = 1;
static constexpr int BTN_KDE_MIDDLE = 2;
static constexpr int BTN_KDE_RIGHT = 3;

class Xkb
{
public:
    Xkb()
    {
        m_ctx.reset(xkb_context_new(XKB_CONTEXT_NO_FLAGS));
        m_keymap.reset(xkb_keymap_new_from_names(m_ctx.get(), nullptr, XKB_KEYMAP_COMPILE_NO_FLAGS));
        m_state.reset(xkb_state_new(m_keymap.get()));
    }

    Xkb(int keymapFd, int size)
    {
        m_ctx.reset(xkb_context_new(XKB_CONTEXT_NO_FLAGS));
        char *map = static_cast<char *>(mmap(nullptr, size, PROT_READ, MAP_PRIVATE, keymapFd, 0));
        m_keymap.reset(xkb_keymap_new_from_buffer(m_ctx.get(), map, size, XKB_KEYMAP_FORMAT_TEXT_V1, XKB_KEYMAP_COMPILE_NO_FLAGS));
        munmap(map, size);
        close(keymapFd);
        m_state.reset(xkb_state_new(m_keymap.get()));
    }

    // Returns evdev scancode from keysym, or 0 if not found.
    // Searches level 0 (unshifted) only. For shifted characters, the caller
    // handles the Shift modifier separately before/after the keypress.
    uint32_t keycodeFromKeysym(xkb_keysym_t sym) const
    {
        if (!m_keymap)
            return 0;

        xkb_keycode_t min = xkb_keymap_min_keycode(m_keymap.get());
        xkb_keycode_t max = xkb_keymap_max_keycode(m_keymap.get());

        // First try level 0 (unshifted)
        for (xkb_keycode_t code = min; code <= max; code++) {
            const xkb_keysym_t *syms;
            int num_syms = xkb_keymap_key_get_syms_by_level(m_keymap.get(), code, 0, 0, &syms);
            for (int i = 0; i < num_syms; i++) {
                if (syms[i] == sym) {
                    return code - min + 1;
                }
            }
        }

        // If not found at level 0, try level 1 (shifted)
        // Return positive evdev code since we handle shift separately
        for (xkb_keycode_t code = min; code <= max; code++) {
            const xkb_keysym_t *syms;
            int num_syms = xkb_keymap_key_get_syms_by_level(m_keymap.get(), code, 0, 1, &syms);
            for (int i = 0; i < num_syms; i++) {
                if (syms[i] == sym) {
                    return code - min + 1;
                }
            }
        }

        return 0;
    }

    int keymapSize() const
    {
        if (!m_keymap)
            return 0;
        char *keymapString = xkb_keymap_get_as_string(m_keymap.get(), XKB_KEYMAP_FORMAT_TEXT_V1);
        if (!keymapString)
            return 0;
        int size = strlen(keymapString) + 1;
        free(keymapString);
        return size;
    }

    bool writeKeymapToFd(int fd) const
    {
        if (!m_keymap)
            return false;
        char *keymapString = xkb_keymap_get_as_string(m_keymap.get(), XKB_KEYMAP_FORMAT_TEXT_V1);
        if (!keymapString)
            return false;
        int size = strlen(keymapString) + 1;
        ssize_t written = write(fd, keymapString, size);
        free(keymapString);
        return written == size;
    }

    xkb_keymap *keymap() const
    {
        return m_keymap.get();
    }

private:
    struct XkbContextDeleter {
        void operator()(xkb_context *ctx)
        {
            xkb_context_unref(ctx);
        }
    };
    struct XkbKeymapDeleter {
        void operator()(xkb_keymap *km)
        {
            xkb_keymap_unref(km);
        }
    };
    struct XkbStateDeleter {
        void operator()(xkb_state *state)
        {
            xkb_state_unref(state);
        }
    };

    std::unique_ptr<xkb_context, XkbContextDeleter> m_ctx;
    std::unique_ptr<xkb_keymap, XkbKeymapDeleter> m_keymap;
    std::unique_ptr<xkb_state, XkbStateDeleter> m_state;
};

HyprlandRemoteInput::HyprlandRemoteInput(QObject *parent)
    : AbstractRemoteInput(parent)
{
    if (connectToCompositor()) {
        m_ready = true;
        qWarning() << "Hyprland backend connected successfully";
    } else {
        qWarning() << "Hyprland backend failed to connect to compositor";
    }
}

HyprlandRemoteInput::~HyprlandRemoteInput()
{
    disconnectFromCompositor();
}

bool HyprlandRemoteInput::isAvailable()
{
    // Quick environment check first
    if (QGuiApplication::platformName() != QLatin1String("wayland")) {
        return false;
    }

    // Open a temporary connection to check for the protocol
    wl_display *display = wl_display_connect(nullptr);
    if (!display) {
        return false;
    }

    struct CheckData {
        bool found = false;
    } data;

    wl_registry *registry = wl_display_get_registry(display);

    auto globalCb = [](void *data, struct wl_registry *, uint32_t, const char *interface, uint32_t) {
        auto *d = static_cast<CheckData *>(data);
        if (strcmp(interface, zwlr_virtual_pointer_manager_v1_interface.name) == 0) {
            d->found = true;
        }
    };

    auto globalRemoveCb = [](void *, struct wl_registry *, uint32_t) {
        // Nothing to do
    };

    static const wl_registry_listener listener = {globalCb, globalRemoveCb};
    wl_registry_add_listener(registry, &listener, &data);
    wl_display_roundtrip(display);

    wl_registry_destroy(registry);
    wl_display_disconnect(display);

    return data.found;
}

bool HyprlandRemoteInput::connectToCompositor()
{
    m_display = wl_display_connect(nullptr);
    if (!m_display) {
        qWarning() << "Failed to connect to Wayland display";
        return false;
    }

    m_registry = wl_display_get_registry(m_display);
    if (!m_registry) {
        qWarning() << "Failed to get Wayland registry";
        wl_display_disconnect(m_display);
        m_display = nullptr;
        return false;
    }

    static const wl_registry_listener listener = {sRegistryGlobal, sRegistryGlobalRemove};
    wl_registry_add_listener(m_registry, &listener, this);
    wl_display_roundtrip(m_display);

    if (!m_pointerManager) {
        qWarning() << "Compositor does not support wlr-virtual-pointer protocol";
        wl_registry_destroy(m_registry);
        wl_display_disconnect(m_display);
        m_registry = nullptr;
        m_display = nullptr;
        return false;
    }

    // Set up socket notifier for Wayland events
    int fd = wl_display_get_fd(m_display);
    m_notifier = new QSocketNotifier(fd, QSocketNotifier::Read, this);
    connect(m_notifier, &QSocketNotifier::activated, this, [this]() {
        wl_display_dispatch(m_display);
    });

    // Initialize xkbcommon for keymap
    m_xkb = std::make_unique<Xkb>();

    ensurePointer();

    return true;
}

void HyprlandRemoteInput::disconnectFromCompositor()
{
    m_ready = false;

    delete m_notifier;
    m_notifier = nullptr;

    if (m_virtualKeyboard) {
        zwp_virtual_keyboard_v1_destroy(m_virtualKeyboard);
        m_virtualKeyboard = nullptr;
    }

    if (m_keyboardManager) {
        zwp_virtual_keyboard_manager_v1_destroy(m_keyboardManager);
        m_keyboardManager = nullptr;
    }

    if (m_virtualPointer) {
        zwlr_virtual_pointer_v1_destroy(m_virtualPointer);
        m_virtualPointer = nullptr;
    }

    if (m_pointerManager) {
        zwlr_virtual_pointer_manager_v1_destroy(m_pointerManager);
        m_pointerManager = nullptr;
    }

    if (m_registry) {
        wl_registry_destroy(m_registry);
        m_registry = nullptr;
    }

    if (m_display) {
        wl_display_flush(m_display);
        wl_display_disconnect(m_display);
        m_display = nullptr;
    }

    m_seat = nullptr;
    m_xkb.reset();
}

void HyprlandRemoteInput::ensurePointer()
{
    if (m_virtualPointer) {
        return;
    }

    if (!m_pointerManager) {
        return;
    }

    // Create virtual pointer - pass seat if we have one
    m_virtualPointer = zwlr_virtual_pointer_manager_v1_create_virtual_pointer(m_pointerManager, m_seat);
    wl_display_flush(m_display);
}

void HyprlandRemoteInput::ensureKeyboard()
{
    if (m_virtualKeyboard) {
        return;
    }

    if (!m_keyboardManager || !m_seat) {
        return;
    }

    m_virtualKeyboard = zwp_virtual_keyboard_manager_v1_create_virtual_keyboard(m_keyboardManager, m_seat);

    // Send keymap
    if (m_xkb && m_xkb->keymap()) {
        // Create a memfd for the keymap
        int keymapFd = memfd_create("kdeconnect-keymap", MFD_CLOEXEC);
        if (keymapFd >= 0) {
            m_xkb->writeKeymapToFd(keymapFd);
            int size = m_xkb->keymapSize();
            lseek(keymapFd, 0, SEEK_SET);

            zwp_virtual_keyboard_v1_keymap(m_virtualKeyboard, XKB_KEYMAP_FORMAT_TEXT_V1, keymapFd, size);
            close(keymapFd);
        }
    }

    wl_display_flush(m_display);
}

void HyprlandRemoteInput::sRegistryGlobal(void *data, struct wl_registry *registry, uint32_t name, const char *interface, uint32_t version)
{
    auto *self = static_cast<HyprlandRemoteInput *>(data);

    if (strcmp(interface, wl_seat_interface.name) == 0) {
        self->m_seat = static_cast<wl_seat *>(wl_registry_bind(registry, name, &wl_seat_interface, std::min(version, 7u)));
    } else if (strcmp(interface, zwlr_virtual_pointer_manager_v1_interface.name) == 0) {
        self->m_pointerManager =
            static_cast<zwlr_virtual_pointer_manager_v1 *>(wl_registry_bind(registry, name, &zwlr_virtual_pointer_manager_v1_interface, std::min(version, 2u)));
    } else if (strcmp(interface, zwp_virtual_keyboard_manager_v1_interface.name) == 0) {
        self->m_keyboardManager =
            static_cast<zwp_virtual_keyboard_manager_v1 *>(wl_registry_bind(registry, name, &zwp_virtual_keyboard_manager_v1_interface, std::min(version, 1u)));
    }
}

void HyprlandRemoteInput::sRegistryGlobalRemove(void *, struct wl_registry *, uint32_t)
{
    // Not needed for this implementation
}

bool HyprlandRemoteInput::hasKeyboardSupport()
{
    return m_keyboardManager != nullptr;
}

bool HyprlandRemoteInput::handlePacket(const NetworkPacket &np)
{
    if (!m_ready) {
        qWarning() << "Hyprland backend not ready, dropping packet";
        return false;
    }

    const float dx = np.get<float>(QStringLiteral("dx"), 0);
    const float dy = np.get<float>(QStringLiteral("dy"), 0);
    const float x = np.get<float>(QStringLiteral("x"), 0);
    const float y = np.get<float>(QStringLiteral("y"), 0);

    const bool isSingleClick = np.get<bool>(QStringLiteral("singleclick"), false);
    const bool isDoubleClick = np.get<bool>(QStringLiteral("doubleclick"), false);
    const bool isMiddleClick = np.get<bool>(QStringLiteral("middleclick"), false);
    const bool isRightClick = np.get<bool>(QStringLiteral("rightclick"), false);
    const bool isSingleHold = np.get<bool>(QStringLiteral("singlehold"), false);
    const bool isSingleRelease = np.get<bool>(QStringLiteral("singlerelease"), false);
    const bool isScroll = np.get<bool>(QStringLiteral("scroll"), false);
    const QString key = np.get<QString>(QStringLiteral("key"), QLatin1String(""));
    const int specialKey = np.get<int>(QStringLiteral("specialKey"), 0);

    // Match the exact logic flow from the original implementations:
    // All non-move events are handled in a single big OR chain
    if (isSingleClick || isDoubleClick || isMiddleClick || isRightClick || isSingleHold || isSingleRelease || isScroll || !key.isEmpty() || specialKey) {
        if (isSingleClick) {
            ensurePointer();
            handlePointerButton(BTN_LEFT, true);
            handlePointerButton(BTN_LEFT, false);
        } else if (isDoubleClick) {
            ensurePointer();
            handlePointerButton(BTN_LEFT, true);
            handlePointerButton(BTN_LEFT, false);
            handlePointerButton(BTN_LEFT, true);
            handlePointerButton(BTN_LEFT, false);
        } else if (isMiddleClick) {
            ensurePointer();
            handlePointerButton(BTN_MIDDLE, true);
            handlePointerButton(BTN_MIDDLE, false);
        } else if (isRightClick) {
            ensurePointer();
            handlePointerButton(BTN_RIGHT, true);
            handlePointerButton(BTN_RIGHT, false);
        } else if (isSingleHold) {
            ensurePointer();
            // For drag'n drop
            handlePointerButton(BTN_LEFT, true);
        } else if (isSingleRelease) {
            ensurePointer();
            handlePointerButton(BTN_LEFT, false);
        } else if (isScroll) {
            ensurePointer();
            handlePointerAxis(dx, dy);
        } else if (specialKey || !key.isEmpty()) {
            // Keyboard input handling (modifiers are press+release per-packet,
            // matching the original implementations exactly)
            const bool ctrl = np.get<bool>(QStringLiteral("ctrl"), false);
            const bool alt = np.get<bool>(QStringLiteral("alt"), false);
            const bool shift = np.get<bool>(QStringLiteral("shift"), false);
            const bool super = np.get<bool>(QStringLiteral("super"), false);

            if (!m_keyboardManager) {
                return true;
            }
            ensureKeyboard();

            // Press modifiers (always, matching original behavior)
            if (ctrl)
                handleKeyboardKeycode(KEY_LEFTCTRL, true);
            if (alt)
                handleKeyboardKeycode(KEY_LEFTALT, true);
            if (shift)
                handleKeyboardKeycode(KEY_LEFTSHIFT, true);
            if (super)
                handleKeyboardKeycode(KEY_LEFTMETA, true);

            if (specialKey) {
                int keycode =
                    (specialKey >= 0 && specialKey < static_cast<int>(sizeof(SpecialKeysMap) / sizeof(SpecialKeysMap[0]))) ? SpecialKeysMap[specialKey] : 0;
                if (keycode) {
                    handleKeyboardKeycode(keycode, true);
                    handleKeyboardKeycode(keycode, false);
                }
            } else if (!key.isEmpty()) {
                // Check if any character needs shift by searching the actual keymap.
                // Handles both uppercase letters and symbols (!@#$ etc.).
                // wlr-virtual-keyboard does not honor modifier state on all compositors,
                // so fall back to wtype for text requiring shift/AltGr.
                bool needsShift = false;
                if (m_xkb && m_xkb->keymap()) {
                    auto *km = m_xkb->keymap();
                    xkb_keycode_t mn = xkb_keymap_min_keycode(km);
                    xkb_keycode_t mx = xkb_keymap_max_keycode(km);
                    for (const QChar ch : key) {
                        auto ks = xkb_utf32_to_keysym(ch.unicode());
                        if (ks == XKB_KEY_NoSymbol)
                            continue;
                        // Check level 0 first
                        bool atLevel0 = false;
                        for (xkb_keycode_t c = mn; c <= mx && !atLevel0; c++) {
                            const xkb_keysym_t *s;
                            int n = xkb_keymap_key_get_syms_by_level(km, c, 0, 0, &s);
                            for (int i = 0; i < n; i++)
                                if (s[i] == ks)
                                    atLevel0 = true;
                        }
                        if (!atLevel0) {
                            // Not at level 0 - must need shift or AltGr
                            needsShift = true;
                            break;
                        }
                    }
                }

                if (needsShift) {
                    // Use wtype for text with uppercase/shifted characters
                    static bool wtypeChecked = false;
                    static bool wtypeOk = false;
                    if (!wtypeChecked) {
                        wtypeChecked = true;
                        wtypeOk = (QProcess::execute(QStringLiteral("which"), {QStringLiteral("wtype")}) == 0);
                    }
                    if (wtypeOk) {
                        QProcess wtype;
                        wtype.start(QStringLiteral("wtype"), {key});
                        wtype.waitForFinished(1000);
                    }
                } else {
                    // Characters at key level 0 (unshifted) - use direct protocol
                    for (const QChar character : key) {
                        const auto keysym = xkb_utf32_to_keysym(character.unicode());
                        if (keysym != XKB_KEY_NoSymbol) {
                            handleKeyboardKeysym(keysym, true);
                            handleKeyboardKeysym(keysym, false);
                        }
                    }
                }
            }

            // Release modifiers (always, matching original behavior)
            if (ctrl)
                handleKeyboardKeycode(KEY_LEFTCTRL, false);
            if (alt)
                handleKeyboardKeycode(KEY_LEFTALT, false);
            if (shift)
                handleKeyboardKeycode(KEY_LEFTSHIFT, false);
            if (super)
                handleKeyboardKeycode(KEY_LEFTMETA, false);
        }
    } else {
        // Mouse move event
        ensurePointer();

        if (dx != 0.0f || dy != 0.0f) {
            handlePointerMotion(dx, dy);
        } else if (np.has(QStringLiteral("x")) || np.has(QStringLiteral("y"))) {
            handlePointerMotionAbsolute(x, y);
        }
    }

    wl_display_flush(m_display);
    return true;
}

void HyprlandRemoteInput::handlePointerMotion(double dx, double dy)
{
    if (!m_virtualPointer) {
        return;
    }

    uint32_t time = QTime::currentTime().msecsSinceStartOfDay();
    zwlr_virtual_pointer_v1_motion(m_virtualPointer, time, wl_fixed_from_double(dx), wl_fixed_from_double(dy));
    handlePointerFrame();
}

void HyprlandRemoteInput::handlePointerMotionAbsolute(double x, double y)
{
    if (!m_virtualPointer) {
        return;
    }

    // The absolute coordinates are normalized 0.0-1.0, and we need screen dimensions
    // We don't have direct screen size access, so we use a default scale
    // The phone provides normalized coordinates, but we need pixel values
    // For now, we scale to a typical 4K display as the max extent
    // A better approach would be to track the wl_output events
    uint32_t time = QTime::currentTime().msecsSinceStartOfDay();

    // Since the protocol expects pixel values, we'll use reasonable defaults.
    // For Hyprland, the absolute coordinates sent from the phone are typically
    // normalized to [0,1] which we can map to the actual output dimensions.
    // If the phone sends raw pixel values, this will be handled correctly.
    uint32_t xExtent = 3840; // Default fallback - will be refined
    uint32_t yExtent = 2160;

    // Try to use a more reasonable extent - these will be updated as we get
    // output information from the compositor. In practice, the phone app
    // typically sends these as proportional coordinates.
    zwlr_virtual_pointer_v1_motion_absolute(m_virtualPointer, time, static_cast<uint32_t>(x * xExtent), static_cast<uint32_t>(y * yExtent), xExtent, yExtent);
    handlePointerFrame();
}

void HyprlandRemoteInput::handlePointerButton(int button, bool pressed)
{
    if (!m_virtualPointer) {
        return;
    }

    uint32_t time = QTime::currentTime().msecsSinceStartOfDay();
    uint32_t state = pressed ? WL_POINTER_BUTTON_STATE_PRESSED : WL_POINTER_BUTTON_STATE_RELEASED;
    zwlr_virtual_pointer_v1_button(m_virtualPointer, time, button, state);
    handlePointerFrame();
}

void HyprlandRemoteInput::handlePointerAxis(double dx, double dy)
{
    if (!m_virtualPointer) {
        return;
    }

    uint32_t time = QTime::currentTime().msecsSinceStartOfDay();

    // KDE Connect sends dx/dy for scrolling, same as the Wayland backend
    // dx = horizontal scroll, dy = vertical scroll
    // Note: Qt/KDE Connect uses inverted vertical scroll compared to protocol

    if (dy != 0.0) {
        zwlr_virtual_pointer_v1_axis_source(m_virtualPointer, WL_POINTER_AXIS_SOURCE_WHEEL);
        zwlr_virtual_pointer_v1_axis(m_virtualPointer, time, WL_POINTER_AXIS_VERTICAL_SCROLL, wl_fixed_from_double(-dy));
    }

    if (dx != 0.0) {
        zwlr_virtual_pointer_v1_axis_source(m_virtualPointer, WL_POINTER_AXIS_SOURCE_WHEEL);
        zwlr_virtual_pointer_v1_axis(m_virtualPointer, time, WL_POINTER_AXIS_HORIZONTAL_SCROLL, wl_fixed_from_double(dx));
    }

    handlePointerFrame();
}

void HyprlandRemoteInput::handlePointerFrame()
{
    if (!m_virtualPointer) {
        return;
    }
    zwlr_virtual_pointer_v1_frame(m_virtualPointer);
}

void HyprlandRemoteInput::handleKeyboardKeycode(int key, bool pressed)
{
    if (!m_virtualKeyboard) {
        return;
    }

    uint32_t time = QTime::currentTime().msecsSinceStartOfDay();
    uint32_t state = pressed ? WL_KEYBOARD_KEY_STATE_PRESSED : WL_KEYBOARD_KEY_STATE_RELEASED;
    zwp_virtual_keyboard_v1_key(m_virtualKeyboard, time, key, state);
}

void HyprlandRemoteInput::handleKeyboardKeysym(uint32_t sym, bool pressed)
{
    if (!m_virtualKeyboard || !m_xkb) {
        return;
    }

    auto code = m_xkb->keycodeFromKeysym(sym);
    if (code) {
        uint32_t time = QTime::currentTime().msecsSinceStartOfDay();
        uint32_t state = pressed ? WL_KEYBOARD_KEY_STATE_PRESSED : WL_KEYBOARD_KEY_STATE_RELEASED;
        zwp_virtual_keyboard_v1_key(m_virtualKeyboard, time, code, state);
    } else {
        qWarning() << "Failed to convert keysym" << sym;
    }
}

#include "moc_hyprlandremoteinput.cpp"
